API_Inventory/API_Inventory/Controllers/ListaMercadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace API_Inventory.Controllers
{
    public class ListaMercadoController : Controller
    {
        // GET: MarketList
        public ActionResult ListaMercadoView()
        {
            return View();
        }
    }
}

API_Inventory/API_Inventory/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace API_Inventory.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Product
        public ActionResult ProductoView()
        {
            return View();
        }
    }
}

API_Inventory/API_Inventory/Views/Shared/Navbar.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Inventory</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active" title="Inicio"><a href="@Url.Action("Index","Home")"><i class="fa fa-home"></i></a></li>
                <li title="Productos"><a href="@Url.Action("ProductoView","Producto")"><i class="fas fa-copyright"></i></a></li>
                <li title="Últimas listas"><a href="@Url.Action("ListaMercadoView","ListaMercado")"><i class="fas fa-list-ol"></i></a></li>
            </ul>
        </div>
    
    </div>
</nav>

API_Inventory/API_Inventory/Views/Shared/PanelContainer.cshtml
<div id="mainPanel" class="panel panel-default">
    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-sm-4 col-xs-6">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fas fa-cart-plus"></i></span>
                        <input type="text" class="form-control" placeholder="Supermercado" aria-describedby="basic-addon1" id="txtSupermercado" required />
                    </div>
                </div>
                <div class="col-sm-4 col-xs-6">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fas fa-dollar-sign"></i></span>
                        <input type="text" class="form-control" placeholder="Gasto total" aria-describedby="basic-addon1" id="txtGasto" required />
                    </div>
                </div>
                <div class="col-sm-4 col-xs-6">
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="far fa-calendar-alt"></i></span>
                        <input type="text" class="form-control" placeholder="Fecha" aria-describedby="basic-addon1" id="txtFecha" required />
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="form-horizontal" id="formBody">
            <div class="form-group">
                <div class="col-sm-8 col-xs-6">
                    <div class="ui-widget">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1"><i class="fas fa-barcode"></i></span>
                            <input type="text" class="form-control inputProducto" placeholder="Producto" aria-describedby="basic-addon1" required />
                        </div>
                    </div>
                </div>
                <div class="col-sm-2 col-xs-3">
                    <input type="text" class="form-control inputCantidad" placeholder="Cantidad" />
                </div>
                <div class="col-sm-2 col-xs-2">
                    <button class="btn btn-success btn-add" onclick="agregarItem()" title="Agregar item"><i class="fas fa-plus"></i></button>
                    <button class="btn btn-danger btnAddProducto" onclick="guardarProductoDesdeLista(this)" title="Agregar producto nuevo"><i class="fas fa-cart-plus"></i></button>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-12">
                <div class="pull-right">
                    <button class="btn btn-inverse" onclick="guardarBorrador()">Guardar Borrador</button>
                    <button class="btn btn-success" onclick="confirmarLista()">Confirmar Lista</button>
                    <button class="btn btn-primary" onclick="imprimirLista()">Imprimir Lista</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ready(function () {
        cargarProductos('LM');
        $('#txtFecha').datepicker();
    });

    function imprimirLista() {

        var items = [];
        var formGroupElements = $('#formBody > .form-group');

        for (var i = 0; i < formGroupElements.length; i++) {

            let formGroup = formGroupElements[i];
            let NombreProducto = $(formGroup).find('.inputProducto').val();
            let CantidadProducto = $(formGroup).find('.inputCantidad').val();
            let productObj = {
                Nombre: NombreProducto,
                Cantidad: CantidadProducto
            };

            items.push(productObj);
        }

        let url = '@Url.Action("ImprimirLista", "Home")?xoItems=' + JSON.stringify(items);
        window.open(url, '_blank');

    }

</script>

API_Inventory/API_Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/font-awesome/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/app")
    @Scripts.Render("~/bundles/font-awesome/js")
    @RenderSection("scripts", required: false)


    @* HEADER *@
    <div class="row">
        <div class="col-sm-12">
            @Html.Partial("Navbar")
        </div>
    </div>

    <div id="mainContainer" class="container">
        @RenderBody()
    </div>

    <script type="text/javascript">

        var arrProductos = [];

    </script>

</body>
</html>